name: Build and push Docker image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build Docker image
        run: docker build -t registry.cn-qingdao.aliyuncs.com/retry/typing-word:latest .

      - name: Push Docker image
        run: docker push registry.cn-qingdao.aliyuncs.com/retry/typing-word:latest
